package client

// Used by potentially shared structs like ApiKeyData if moved here

// This file defines common Go structs used across multiple OpenRouter API methods
// as defined in the OpenAPI specification and derived from various endpoint descriptions.

// --- Error Handling ---

// ErrorResponseWrapper is the top-level structure expected for JSON error responses.
type ErrorResponseWrapper struct {
	Error *ErrorDetails `json:"error"`
}

// ErrorDetails represents the structured error information within the 'error' field.
type ErrorDetails struct {
	Code     int                    `json:"code"`               // Typically matches the HTTP status code.
	Message  string                 `json:"message"`            // Human-readable error description.
	Metadata map[string]interface{} `json:"metadata,omitempty"` // Optional: Provider/moderation details, or other context.
}

// InlineErrorResponse represents error details potentially included within a Choice object
// in a Chat Completion response. It mirrors ErrorDetails for consistency.
// type InlineErrorResponse ErrorDetails // Could use type alias if identical
type InlineErrorResponse struct {
	Code     int                    `json:"code"`
	Message  string                 `json:"message"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// --- Usage and Pricing ---

// ResponseUsage represents the token usage information returned in completion responses.
// Counts are based on a normalized tokenizer (GPT-4o) unless native counts are also requested/provided.
type ResponseUsage struct {
	PromptTokens     int `json:"prompt_tokens"`     // Normalized prompt tokens.
	CompletionTokens int `json:"completion_tokens"` // Normalized completion tokens.
	TotalTokens      int `json:"total_tokens"`      // Sum of normalized prompt and completion tokens.
}

// MaxPrice defines maximum acceptable provider pricing for a request (OpenRouter-specific).
type MaxPrice struct {
	Prompt     *float64 `json:"prompt,omitempty"`     // Max price per million prompt tokens (USD).
	Completion *float64 `json:"completion,omitempty"` // Max price per million completion tokens (USD).
	Request    *float64 `json:"request,omitempty"`    // Max price per request (USD).
	Image      *float64 `json:"image,omitempty"`      // Max price per image (USD).
}

// --- Provider Routing & Preferences (OpenRouter-specific) ---

// ProviderPreferences controls how requests are routed across providers for a specific model.
type ProviderPreferences struct {
	Order             []string `json:"order,omitempty"`              // List of provider names to try in order.
	AllowFallbacks    *bool    `json:"allow_fallbacks,omitempty"`    // Default: true. Allow fallback beyond ordered/top providers.
	RequireParameters *bool    `json:"require_parameters,omitempty"` // Default: false. Only use providers supporting all request parameters.
	DataCollection    *string  `json:"data_collection,omitempty"`    // "allow" (default) or "deny" data collection/training by provider.
	Ignore            []string `json:"ignore,omitempty"`             // List of provider names to exclude.
	Quantizations     []string `json:"quantizations,omitempty"`      // List of acceptable quantization levels (e.g., "fp8", "int4").
	Sort              *string  `json:"sort,omitempty"`               // Sort providers by "price", "throughput", or "latency". Disables load balancing.
}

// --- Tool Calling ---

// Tool represents a tool definition that the model may call.
type Tool struct {
	Type     string              `json:"type"` // Currently only "function" supported.
	Function FunctionDescription `json:"function"`
}

// FunctionDescription describes a function available to the model.
type FunctionDescription struct {
	Name        string      `json:"name"`                  // Required: The name of the function.
	Description string      `json:"description,omitempty"` // Optional: Description for the model.
	Parameters  interface{} `json:"parameters"`            // Required: JSON Schema object describing function parameters. Use map[string]interface{} or a specific struct.
}

// ToolChoice controls which tool (if any) the model should call.
// Can be a string ("none", "auto", "required") or a specific function choice object.
// Use interface{} and type assertions or custom marshal/unmarshal if strict typing is needed.
type ToolChoice interface{} // Represents oneOf: string | object

// Example specific function choice structure (if needed for requests)
type SpecificFunctionChoice struct {
	Type     string         `json:"type"` // Must be "function"
	Function ToolChoiceFunc `json:"function"`
}
type ToolChoiceFunc struct {
	Name string `json:"name"` // Name of the function to call
}

// ToolCall represents a tool call generated by the model in an assistant message.
type ToolCall struct {
	ID       string       `json:"id"`       // Required: ID of the tool call.
	Type     string       `json:"type"`     // Currently only "function".
	Function FunctionCall `json:"function"` // Details of the function called.
}

// FunctionCall represents the function call details within a ToolCall.
type FunctionCall struct {
	Name      string `json:"name"`      // Required: Name of the function called.
	Arguments string `json:"arguments"` // Required: JSON string of arguments passed to the function.
}

// StreamingToolCall represents a tool call delta in a streaming response chunk.
type StreamingToolCall struct {
	Index    *int                   `json:"index,omitempty"` // Index of the tool call.
	ID       *string                `json:"id,omitempty"`    // ID, usually in first chunk for the call.
	Type     *string                `json:"type,omitempty"`  // Type ("function").
	Function *StreamingFunctionCall `json:"function,omitempty"`
}

// StreamingFunctionCall represents the function call delta within a StreamingToolCall chunk.
type StreamingFunctionCall struct {
	Name      *string `json:"name,omitempty"`      // Function name, usually in first chunk.
	Arguments *string `json:"arguments,omitempty"` // Argument JSON string chunks.
}

// --- Logprobs ---

// LogprobResult represents log probability information for a choice.
type LogprobResult struct {
	Content []Logprob `json:"content,omitempty"` // Can be null
}

// Logprob represents log probability information for a single token.
type Logprob struct {
	Token       string       `json:"token"`
	Logprob     float64      `json:"logprob"`
	Bytes       []int        `json:"bytes,omitempty"`        // Optional: UTF-8 byte representation. Can be null.
	TopLogprobs []TopLogprob `json:"top_logprobs,omitempty"` // Optional: If top_logprobs requested. Can be null.
}

// TopLogprob represents one of the top log probability tokens at a specific position.
type TopLogprob struct {
	Token   string  `json:"token"`
	Logprob float64 `json:"logprob"`
	Bytes   []int   `json:"bytes,omitempty"` // Optional: UTF-8 byte representation. Can be null.
}

// --- Reasoning Tokens (OpenRouter-specific) ---

// ReasoningConfig controls reasoning token behavior for models that support it.
type ReasoningConfig struct {
	Effort    *string `json:"effort,omitempty"`     // "low", "medium", "high". Mutually exclusive with MaxTokens.
	MaxTokens *int    `json:"max_tokens,omitempty"` // Specific token limit. Mutually exclusive with Effort.
	Exclude   *bool   `json:"exclude,omitempty"`    // Default: false. If true, reasoning is used but not returned.
}

// --- Web Search / Annotations ---

// Annotation represents metadata attached to a message, like a web citation.
type Annotation struct {
	Type        string       `json:"type"`                   // e.g., "url_citation"
	URLCitation *URLCitation `json:"url_citation,omitempty"` // Present if type is "url_citation"
	// Add other annotation types here if they exist
}

// URLCitation provides details about a web search result citation.
type URLCitation struct {
	URL        string `json:"url"`                   // The URL cited.
	Title      string `json:"title,omitempty"`       // Title of the web page.
	Content    string `json:"content,omitempty"`     // Content snippet (added by OpenRouter if available).
	StartIndex *int   `json:"start_index,omitempty"` // Start index of citation in message content.
	EndIndex   *int   `json:"end_index,omitempty"`   // End index of citation in message content.
}

// --- Miscellaneous ---

// StringOrArray is a helper type to handle JSON fields that can be either
// a single string or an array of strings (like the 'stop' parameter).
// Requires custom JSON marshaling/unmarshaling logic.
type StringOrArray interface{} // Needs custom handling or use interface{} + type assertion

// Custom Marshaler/Unmarshaler for StringOrArray (Example Implementation)
// Note: Implementing this robustly can be complex depending on exact needs.
// Using interface{} and type checking in the calling code might be simpler.

/*
type StringOrArrayImpl struct {
	Value interface{} // Stores either string or []string
}

func (s *StringOrArrayImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.Value)
}

func (s *StringOrArrayImpl) UnmarshalJSON(data []byte) error {
	var strVal string
	if err := json.Unmarshal(data, &strVal); err == nil {
		s.Value = strVal
		return nil
	}

	var arrVal []string
	if err := json.Unmarshal(data, &arrVal); err == nil {
		s.Value = arrVal
		return nil
	}

	return fmt.Errorf("data '%s' is not a string or an array of strings", string(data))
}

// Make sure to use *StringOrArrayImpl in request structs if using this approach.
*/
